lookup: re-add bluebird
nodejs/citgm pull request #989
Opened 2023-09-29 09:34 UTC by alfonsograziano

##### Checklist

- [ x] `npm test` passes
- [x ] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

2023-09-29 17:15 UTC, Trott commented
It will take a while for the job to start, but https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3285/ will hopefully have bluebird results.

2023-09-29 18:24 UTC, Trott requested changes
Bluebird passes locally but fails in Jenkins CI.

2023-09-29 18:24 UTC, Trott commented on lib/lookup.json
> +    "maintainers": "petkaantonov"
```suggestion
    "maintainers": "petkaantonov",
    "stripAnsi": true
```

2023-09-29 18:31 UTC, Trott commented
Running again with ANSI stipping enabled, just in case that's somehow the source of the problem. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3286/

2023-09-29 18:44 UTC, alfonsograziano commented
Still failing, to be honest I'm not sure if it is a legittimate issue or a false positive

2023-09-29 20:51 UTC, Trott commented
The ANSI-stripping didn't do anything either. Harumph.

> (I mean when locally it works but fails on the CI pipeline)

I wish I had an answer. I have no idea why this passes locally and fails *everywhere* in CI. Must be something in the CI configuration somewhere, but I'm not even sure what to look for. Suggestions welcome.....

@nodejs/build 

TBH, unless bluebird is important to you personally, I'm not sure this is worth a lot of effort. Bluebird hasn't seen a new version if 4 years and is likely mostly obsolete at this point. Its current download stats are an artifact of its enormous popularity and utility in the past.

2023-10-02 07:10 UTC, alfonsograziano commented
Good point, probably is not worth to add this package. Is definitely weird that the pipeline is failing on the CI. If the same happens with other packages, then probably is worth to investigate. 

I'll close this PR for now and I'll focus on other packages that we should add due to their popularity in the ecosystem. 

Thanks for your support, really appreciated 😃

2023-10-02 07:10 UTC, closed without merging